// <auto-generated />
using System;
using Jellyfin.Database.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Database.Providers.Galera.Migrations
{
    [DbContext(typeof(JellyfinDbContext))]
    partial class JellyfinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.AccessSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<double>("EndHour")
                        .HasColumnType("double");

                    b.Property<double>("StartHour")
                        .HasColumnType("double");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccessSchedules");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("DateCreated")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("LogSeverity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Overview")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<string>("ShortOverview")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.AncestorId", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("ItemId", "ParentItemId");

                    b.HasIndex("ParentItemId");

                    b.ToTable("AncestorIds");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.AttachmentStreamInfo", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Codec")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CodecTag")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Filename")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("MimeType")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("ItemId", "Index");

                    b.ToTable("AttachmentStreamInfos");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Album")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("AlbumArtists")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Artists")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("Audio")
                        .HasColumnType("int");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CleanName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double?>("CommunityRating")
                        .HasColumnType("double");

                    b.Property<double?>("CriticRating")
                        .HasColumnType("double");

                    b.Property<string>("CustomRating")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long?>("DateCreated")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateLastMediaAdded")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateLastRefreshed")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateLastSaved")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModified")
                        .HasColumnType("bigint");

                    b.Property<long?>("EndDate")
                        .HasColumnType("bigint");

                    b.Property<string>("EpisodeTitle")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ExternalSeriesId")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ExternalServiceId")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("ExtraType")
                        .HasColumnType("int");

                    b.Property<string>("ForcedSortName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Genres")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InheritedParentalRatingSubValue")
                        .HasColumnType("int");

                    b.Property<int?>("InheritedParentalRatingValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInMixedFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMovie")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSeries")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVirtualItem")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("LUFS")
                        .HasColumnType("double");

                    b.Property<string>("MediaType")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double?>("NormalizationGain")
                        .HasColumnType("double");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Overview")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ParentIndexNumber")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("PreferredMetadataCountryCode")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("PreferredMetadataLanguage")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long?>("PremiereDate")
                        .HasColumnType("bigint");

                    b.Property<string>("PresentationUniqueKey")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid?>("PrimaryVersionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductionLocations")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<long?>("RunTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SeasonName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SeriesName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("SeriesPresentationUniqueKey")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ShowId")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SortName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long?>("StartDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Studios")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid?>("TopParentId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("TotalBitrate")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("UnratedType")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.HasIndex("PresentationUniqueKey")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.HasIndex("PrimaryVersionId")
                        .HasFilter("\"PrimaryVersionId\" IS NOT NULL");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SeriesName")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.HasIndex("ExtraType", "OwnerId");

                    b.HasIndex("TopParentId", "Id");

                    b.HasIndex("Type", "CleanName")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 255 });

                    b.HasIndex("TopParentId", "Type", "IsVirtualItem")
                        .HasFilter("\"PrimaryVersionId\" IS NULL AND (\"OwnerId\" IS NULL OR \"ExtraType\" IS NOT NULL)")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 255, 0 });

                    b.HasIndex("Type", "TopParentId", "Id")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0, 0 });

                    b.HasIndex("Type", "TopParentId", "PresentationUniqueKey")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0, 255 });

                    b.HasIndex("Type", "TopParentId", "SortName")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0, 255 });

                    b.HasIndex("Type", "TopParentId", "StartDate")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0, 0 });

                    b.HasIndex("MediaType", "TopParentId", "IsVirtualItem", "PresentationUniqueKey")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0, 0, 255 });

                    b.HasIndex("TopParentId", "IsFolder", "IsVirtualItem", "DateCreated");

                    b.HasIndex("TopParentId", "MediaType", "IsVirtualItem", "DateCreated")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 255, 0, 0 });

                    b.HasIndex("TopParentId", "Type", "IsVirtualItem", "DateCreated")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 255, 0, 0 });

                    b.HasIndex("Type", "SeriesPresentationUniqueKey", "IsFolder", "IsVirtualItem")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 255, 0, 0 });

                    b.HasIndex("Type", "SeriesPresentationUniqueKey", "ParentIndexNumber", "IndexNumber")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 255, 0, 0 });

                    b.HasIndex("Type", "SeriesPresentationUniqueKey", "PresentationUniqueKey", "SortName")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 192, 192, 192, 192 });

                    b.HasIndex("IsFolder", "TopParentId", "IsVirtualItem", "PresentationUniqueKey", "DateCreated")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0, 255, 0 });

                    b.HasIndex("Type", "TopParentId", "IsVirtualItem", "PresentationUniqueKey", "DateCreated")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0, 0, 255, 0 });

                    b.ToTable("BaseItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsFolder = false,
                            IsInMixedFolder = false,
                            IsLocked = false,
                            IsMovie = false,
                            IsRepeat = false,
                            IsSeries = false,
                            IsVirtualItem = false,
                            Name = "This is a placeholder item for UserData that has been detached from its original item",
                            Type = "PLACEHOLDER"
                        });
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemImageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Blurhash")
                        .HasColumnType("longblob");

                    b.Property<long?>("DateModified")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ImageType");

                    b.ToTable("BaseItemImageInfos");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemMetadataField", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BaseItemMetadataFields");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemProvider", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ProviderValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("ItemId", "ProviderId");

                    b.HasIndex("ProviderId", "ItemId", "ProviderValue")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 220 });

                    b.ToTable("BaseItemProviders");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemTrailerType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BaseItemTrailerTypes");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Chapter", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ChapterIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ImageDateModified")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("StartPositionTicks")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId", "ChapterIndex");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.CustomItemDisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId", "Client", "Key")
                        .IsUnique();

                    b.ToTable("CustomItemDisplayPreferences");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.DisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChromecastVersion")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("DashboardTheme")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<bool>("EnableNextVideoInfoOverlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IndexBy")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ScrollDirection")
                        .HasColumnType("int");

                    b.Property<bool>("ShowBackdrop")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowSidebar")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SkipBackwardLength")
                        .HasColumnType("int");

                    b.Property<int>("SkipForwardLength")
                        .HasColumnType("int");

                    b.Property<string>("TvHome")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId", "Client")
                        .IsUnique();

                    b.ToTable("DisplayPreferences");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.HomeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayPreferencesId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisplayPreferencesId");

                    b.ToTable("HomeSection");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ImageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("LastModified")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ImageInfos");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ItemDisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("IndexBy")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("RememberIndexing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberSorting")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SortBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ViewType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ItemDisplayPreferences");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ItemValue", b =>
                {
                    b.Property<Guid>("ItemValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CleanValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("varchar(700)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("ItemValueId");

                    b.HasIndex("Type", "CleanValue")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 255 });

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("ItemValues");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ItemValueMap", b =>
                {
                    b.Property<Guid>("ItemValueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("ItemValueId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemValuesMap");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.KeyframeData", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("KeyframeTicks")
                        .HasColumnType("longtext");

                    b.Property<long>("TotalDuration")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId");

                    b.ToTable("KeyframeData");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.LinkedChildEntity", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ChildType")
                        .HasColumnType("int");

                    b.HasKey("ParentId", "SortOrder");

                    b.HasIndex("ChildId", "ChildType");

                    b.HasIndex("ParentId", "ChildType");

                    b.ToTable("LinkedChildren", (string)null);
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.MediaSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("EndTicks")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SegmentProviderId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("StartTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MediaSegments");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.MediaStreamInfo", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("int");

                    b.Property<string>("AspectRatio")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double?>("AverageFrameRate")
                        .HasColumnType("double");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("int");

                    b.Property<int?>("BitRate")
                        .HasColumnType("int");

                    b.Property<int?>("BlPresentFlag")
                        .HasColumnType("int");

                    b.Property<string>("ChannelLayout")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("Channels")
                        .HasColumnType("int");

                    b.Property<string>("Codec")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CodecTag")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CodecTimeBase")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ColorPrimaries")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ColorSpace")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ColorTransfer")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("DvBlSignalCompatibilityId")
                        .HasColumnType("int");

                    b.Property<int?>("DvLevel")
                        .HasColumnType("int");

                    b.Property<int?>("DvProfile")
                        .HasColumnType("int");

                    b.Property<int?>("DvVersionMajor")
                        .HasColumnType("int");

                    b.Property<int?>("DvVersionMinor")
                        .HasColumnType("int");

                    b.Property<int?>("ElPresentFlag")
                        .HasColumnType("int");

                    b.Property<bool?>("Hdr10PlusPresentFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAnamorphic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsAvc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForced")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsHearingImpaired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsInterlaced")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyFrames")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Language")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double?>("Level")
                        .HasColumnType("double");

                    b.Property<string>("NalLengthSize")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Path")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("PixelFormat")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Profile")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double?>("RealFrameRate")
                        .HasColumnType("double");

                    b.Property<int?>("RefFrames")
                        .HasColumnType("int");

                    b.Property<int?>("Rotation")
                        .HasColumnType("int");

                    b.Property<int?>("RpuPresentFlag")
                        .HasColumnType("int");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("int");

                    b.Property<int>("StreamType")
                        .HasColumnType("int");

                    b.Property<string>("TimeBase")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "StreamIndex");

                    b.HasIndex("StreamType", "ItemId", "Language", "IsExternal")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 255, 0 });

                    b.ToTable("MediaStreamInfos");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.People", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("PersonType")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.PeopleBaseItemMap", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PeopleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("ListOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "PeopleId", "Role");

                    b.HasIndex("ItemId", "ListOrder");

                    b.HasIndex("ItemId", "SortOrder");

                    b.HasIndex("PeopleId", "ItemId");

                    b.ToTable("PeopleBaseItemMap");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Value")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Security.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("DateCreated")
                        .HasColumnType("bigint");

                    b.Property<long>("DateLastActivity")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Security.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("DateCreated")
                        .HasColumnType("bigint");

                    b.Property<long>("DateLastActivity")
                        .HasColumnType("bigint");

                    b.Property<long>("DateModified")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken", "DateLastActivity")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255, 0 });

                    b.HasIndex("DeviceId", "DateLastActivity");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Security.DeviceOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceOptions");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.TrickplayInfo", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<int>("ThumbnailCount")
                        .HasColumnType("int");

                    b.Property<int>("TileHeight")
                        .HasColumnType("int");

                    b.Property<int>("TileWidth")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "Width");

                    b.ToTable("TrickplayInfos");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudioLanguagePreference")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("AuthenticationProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("CastReceiverId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<bool>("DisplayCollectionsView")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DisplayMissingEpisodes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableAutoLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableLocalPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableNextEpisodeAutoPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableUserPreferenceAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HidePlayedInLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("InternalId")
                        .HasColumnType("bigint");

                    b.Property<int>("InvalidLoginAttemptCount")
                        .HasColumnType("int");

                    b.Property<long?>("LastActivityDate")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastLoginDate")
                        .HasColumnType("bigint");

                    b.Property<int?>("LoginAttemptsBeforeLockout")
                        .HasColumnType("int");

                    b.Property<int>("MaxActiveSessions")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParentalRatingScore")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParentalRatingSubScore")
                        .HasColumnType("int");

                    b.Property<bool>("MustUpdatePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Password")
                        .HasMaxLength(65535)
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("PasswordResetProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<bool>("PlayDefaultAudioTrack")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberAudioSelections")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberSubtitleSelections")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RemoteClientBitrateLimit")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<string>("SubtitleLanguagePreference")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("SubtitleMode")
                        .HasColumnType("int");

                    b.Property<int>("SyncPlayAccess")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.UserData", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomDataKey")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int?>("AudioStreamIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("LastPlayedDate")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Likes")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("bigint");

                    b.Property<bool>("Played")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<long?>("RetentionDate")
                        .HasColumnType("bigint");

                    b.Property<int?>("SubtitleStreamIndex")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "UserId", "CustomDataKey");

                    b.HasIndex("ItemId", "UserId", "IsFavorite");

                    b.HasIndex("ItemId", "UserId", "LastPlayedDate");

                    b.HasIndex("ItemId", "UserId", "PlaybackPositionTicks");

                    b.HasIndex("ItemId", "UserId", "Played");

                    b.HasIndex("UserId", "IsFavorite", "ItemId");

                    b.HasIndex("UserId", "ItemId", "LastPlayedDate");

                    b.HasIndex("UserId", "Played", "ItemId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.AccessSchedule", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", null)
                        .WithMany("AccessSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.AncestorId", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Parents")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "ParentItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.AttachmentStreamInfo", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemEntity", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Owner")
                        .WithMany("Extras")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "DirectParent")
                        .WithMany("DirectChildren")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DirectParent");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemImageInfo", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemMetadataField", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("LockedFields")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemProvider", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Provider")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemTrailerType", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("TrailerTypes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Chapter", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Chapters")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.DisplayPreferences", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", null)
                        .WithMany("DisplayPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.HomeSection", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.DisplayPreferences", null)
                        .WithMany("HomeSections")
                        .HasForeignKey("DisplayPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ImageInfo", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", null)
                        .WithOne("ProfileImage")
                        .HasForeignKey("Jellyfin.Database.Implementations.Entities.ImageInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ItemDisplayPreferences", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", null)
                        .WithMany("ItemDisplayPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ItemValueMap", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("ItemValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellyfin.Database.Implementations.Entities.ItemValue", "ItemValue")
                        .WithMany("BaseItemsMap")
                        .HasForeignKey("ItemValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemValue");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.KeyframeData", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.LinkedChildEntity", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Child")
                        .WithMany("LinkedChildOfEntities")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Parent")
                        .WithMany("LinkedChildEntities")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.MediaStreamInfo", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("MediaStreams")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.PeopleBaseItemMap", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Peoples")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellyfin.Database.Implementations.Entities.People", "People")
                        .WithMany("BaseItems")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("People");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Permission", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Preference", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", null)
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.Security.Device", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.UserData", b =>
                {
                    b.HasOne("Jellyfin.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("UserData")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellyfin.Database.Implementations.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.BaseItemEntity", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Children");

                    b.Navigation("DirectChildren");

                    b.Navigation("Extras");

                    b.Navigation("Images");

                    b.Navigation("ItemValues");

                    b.Navigation("LinkedChildEntities");

                    b.Navigation("LinkedChildOfEntities");

                    b.Navigation("LockedFields");

                    b.Navigation("MediaStreams");

                    b.Navigation("Parents");

                    b.Navigation("Peoples");

                    b.Navigation("Provider");

                    b.Navigation("TrailerTypes");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.DisplayPreferences", b =>
                {
                    b.Navigation("HomeSections");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.ItemValue", b =>
                {
                    b.Navigation("BaseItemsMap");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.People", b =>
                {
                    b.Navigation("BaseItems");
                });

            modelBuilder.Entity("Jellyfin.Database.Implementations.Entities.User", b =>
                {
                    b.Navigation("AccessSchedules");

                    b.Navigation("DisplayPreferences");

                    b.Navigation("ItemDisplayPreferences");

                    b.Navigation("Permissions");

                    b.Navigation("Preferences");

                    b.Navigation("ProfileImage");
                });
#pragma warning restore 612, 618
        }
    }
}
